"""test

Revision ID: 83c50f29925d
Revises: 
Create Date: 2025-10-02 16:27:31.921522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c50f29925d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('_session_info_uc'), 'longterm_memory', type_='unique')
    op.create_unique_constraint('_info_type_uc', 'longterm_memory', ['info_type'])
    op.create_unique_constraint(None, 'longterm_memory', ['info_type'])
    op.drop_column('longterm_memory', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('longterm_memory', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'longterm_memory', type_='unique')
    op.drop_constraint('_info_type_uc', 'longterm_memory', type_='unique')
    op.create_unique_constraint(op.f('_session_info_uc'), 'longterm_memory', ['session_id', 'info_type'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
